# Generated by Django 3.0.5 on 2020-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_password', models.CharField(max_length=15)),
                ('emp_designation', models.CharField(max_length=20)),
                ('emp_adress', models.CharField(max_length=50)),
                ('emp_contact', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
