# Generated by Django 3.0.5 on 2020-08-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='recurt',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('oppcode', models.IntegerField()),
                ('quali', models.CharField(max_length=30)),
                ('startdate', models.DateField()),
                ('age', models.IntegerField()),
                ('lastdate', models.DateField()),
                ('deptid', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('des', models.CharField(max_length=30)),
                ('res', models.CharField(max_length=20)),
                ('cno', models.IntegerField()),
            ],
        ),
    ]
