# Generated by Django 2.2.2 on 2020-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recurt'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('schedule_date', models.DateField()),
            ],
        ),
    ]
