# Generated by Django 2.2.2 on 2020-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201023_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurt',
            name='lastdate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='recurt',
            name='startdate',
            field=models.CharField(max_length=20),
        ),
    ]
