# Generated by Django 2.2.2 on 2020-10-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201023_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='schedule_date',
            field=models.CharField(max_length=30),
        ),
    ]
