# Generated by Django 2.2.2 on 2020-10-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201027_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalized_candiadates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_applicant_id', models.IntegerField()),
                ('f_emp_id', models.IntegerField()),
                ('f_schedule_date', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
