# Generated by Django 2.2.2 on 2020-10-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_finalized_candiadates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalized_candiadates',
            name='result',
            field=models.CharField(max_length=18),
        ),
    ]
