# Generated by Django 2.2.2 on 2020-12-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201101_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_application_form',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
