# Generated by Django 2.2.2 on 2020-12-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201201_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_application_form',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
