# Generated by Django 2.2.2 on 2020-12-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201201_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_application_form',
            name='mobile_no',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_contact',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recurt',
            name='cno',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recurt',
            name='oppcode',
            field=models.IntegerField(unique=True),
        ),
    ]
